"""
Quick setup script to create .env file with proper configuration.
Run this script to interactively set up your environment variables.
"""

import os
from pathlib import Path


def setup_env():
    """Interactive setup for .env file."""
    print("=" * 60)
    print("Infinity8 Backend - Environment Setup")
    print("=" * 60)
    print()
    
    # Check if .env already exists
    env_file = Path(__file__).parent / ".env"
    if env_file.exists():
        response = input(".env file already exists. Overwrite? (y/N): ")
        if response.lower() != 'y':
            print("Setup cancelled.")
            return
    
    print("Please provide the following configuration values:")
    print("(Press Enter to skip optional values)\n")
    
    # Collect required variables
    config = {}
    
    # Required
    config["OPENAI_API_KEY"] = input("OpenAI API Key: ").strip()
    config["SUPABASE_URL"] = input("Supabase URL: ").strip()
    config["SUPABASE_SERVICE_KEY"] = input("Supabase Service Key: ").strip()
    config["STRIPE_SECRET_KEY"] = input("Stripe Secret Key: ").strip()
    
    # Optional but important
    config["STRIPE_WEBHOOK_SECRET"] = input("Stripe Webhook Secret (optional): ").strip()
    config["STRIPE_PUBLISHABLE_KEY"] = input("Stripe Publishable Key (optional): ").strip()
    
    # Email configuration
    print("\n" + "=" * 60)
    print("EMAIL CONFIGURATION (Required for booking confirmations)")
    print("Sign up at https://resend.com to get your API key")
    print("=" * 60)
    config["RESEND_API_KEY"] = input("Resend API Key: ").strip()
    config["RESEND_FROM"] = input("Resend From Email (default: onboarding@resend.dev): ").strip() or "onboarding@resend.dev"
    
    # Frontend URL
    config["FRONTEND_URL"] = input("Frontend URL (default: http://localhost:3000): ").strip() or "http://localhost:3000"
    
    # Write to .env file
    with open(env_file, "w") as f:
        f.write("# Infinity8 Backend Configuration\n")
        f.write("# Generated by setup_env.py\n\n")
        
        f.write("# OpenAI Configuration\n")
        f.write(f"OPENAI_API_KEY={config['OPENAI_API_KEY']}\n")
        f.write("OPENAI_MODEL=gpt-4o-mini\n\n")
        
        f.write("# Supabase Configuration\n")
        f.write(f"SUPABASE_URL={config['SUPABASE_URL']}\n")
        f.write(f"SUPABASE_SERVICE_KEY={config['SUPABASE_SERVICE_KEY']}\n")
        f.write("SUPABASE_JWT_SECRET=\n\n")
        
        f.write("# Stripe Configuration\n")
        f.write(f"STRIPE_SECRET_KEY={config['STRIPE_SECRET_KEY']}\n")
        f.write(f"STRIPE_WEBHOOK_SECRET={config.get('STRIPE_WEBHOOK_SECRET', '')}\n")
        f.write(f"STRIPE_PUBLISHABLE_KEY={config.get('STRIPE_PUBLISHABLE_KEY', '')}\n\n")
        
        f.write("# Resend Email Configuration\n")
        f.write(f"RESEND_API_KEY={config['RESEND_API_KEY']}\n")
        f.write(f"RESEND_FROM={config['RESEND_FROM']}\n\n")
        
        f.write("# Frontend Configuration\n")
        f.write(f"FRONTEND_URL={config['FRONTEND_URL']}\n\n")
        
        f.write("# Optional: SMTP Configuration (alternative to Resend)\n")
        f.write("SMTP_HOST=\n")
        f.write("SMTP_PORT=587\n")
        f.write("SMTP_USERNAME=\n")
        f.write("SMTP_PASSWORD=\n")
        f.write("SMTP_FROM=\n")
        f.write("SMTP_USE_TLS=True\n")
    
    print("\n" + "=" * 60)
    print(f"✅ Configuration saved to: {env_file}")
    print("=" * 60)
    print("\nNext steps:")
    print("1. Review the .env file and update any values as needed")
    print("2. Restart your backend server: uvicorn app.main:app --reload")
    print("3. Make a test booking to verify email notifications work")
    print("\nFor more details, see: backend/EMAIL_SETUP.md")


if __name__ == "__main__":
    try:
        setup_env()
    except KeyboardInterrupt:
        print("\n\nSetup cancelled by user.")
    except Exception as e:
        print(f"\n❌ Error: {e}")
        print("Please create the .env file manually. See backend/EMAIL_SETUP.md for details.")







